platform :ios, '8.0'
use_frameworks!

target 'ColourfulBall' do

pod 'RxSwift',    '~> 3.0'
pod 'RxCocoa',    '~> 3.0'

pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end

